---
name: TwitterSigns
author:  Ad5001
version: 1.0
api: [2.0.0]
main: Ad5001\TwitterSigns\Main
description: "Show followers of someone on a sign !"
website: "https://github.com/Ad5001/TwitterSigns"
commands: []
permissions:
    twittersigns.remove:
      default: op
    twittersigns.create:
      default: op
...